# Generated by Django 6.0.3 on 2026-03-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
