# Generated by Django 6.0.3 on 2026-03-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='uploadedmedia',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_sub',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='sender_sub',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
