services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      # DEV ONLY (Windows/Docker): szybkie obejście pg_hba
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media:/app/media
      - staticfiles:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_COGNITO_DOMAIN_FULL: ${VITE_COGNITO_DOMAIN_FULL}
        VITE_COGNITO_CLIENT_ID: ${VITE_COGNITO_CLIENT_ID}
        VITE_COGNITO_REDIRECT_URI: ${VITE_COGNITO_REDIRECT_URI}
        VITE_COGNITO_LOGOUT_URI: ${VITE_COGNITO_LOGOUT_URI}
    env_file:
      - .env
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
      VITE_COGNITO_DOMAIN_FULL: ${VITE_COGNITO_DOMAIN_FULL}
      VITE_COGNITO_CLIENT_ID: ${VITE_COGNITO_CLIENT_ID}
      VITE_COGNITO_REDIRECT_URI: ${VITE_COGNITO_REDIRECT_URI}
      VITE_COGNITO_LOGOUT_URI: ${VITE_COGNITO_LOGOUT_URI}
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
  media:
  staticfiles: